import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box'
import Container from '@mui/material/Container'

const HeroSection = ({ mode }) => {
  const gradientTextStyle = {
    background: 'linear-gradient(to right, #007CF0, #00DFD8)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text'
  }

  return (
    <Box
      sx={{
        py: { xs: 10, md: 16 },
        textAlign: 'center',
      }}
    >
      <Container maxWidth='lg' >
        <Typography
          variant='h2'
          component='h1'
          sx={{
            fontSize: { xs: '2.5rem', md: '4rem' },
            fontWeight: 900,
            mb: 3,
            lineHeight: 1.2
          }}
        >
          <span style={gradientTextStyle}>NUTRICH.IO</span>
          <br />
          What to Eat? Now You Know.
        </Typography>
        <Typography
          variant='h6'
          sx={{
            color: 'text.secondary',
            maxWidth: '800px',
            mx: 'auto',
            mb: 5
          }}
        >
          Stop guessing and start glowing. Get unique meal plans generated by artificial intelligence, perfectly
          tailored to your individual data, goals, and preferences. Transform your health with your own daily nutrition
          assistant.
        </Typography>
        <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center', flexWrap: 'wrap' }}>
          <Button
            variant='contained'
            size='large'
            sx={{
              background: 'linear-gradient(to right, #007CF0, #00DFD8)',
              px: 4,
              py: 1.5,
              fontSize: '1.1rem',
              fontWeight: 'bold'
            }}
          >
            Create My Personal Plan
          </Button>
          <Button
            variant='outlined'
            size='large'
            sx={{
              px: 4,
              py: 1.5,
              fontSize: '1.1rem',
              fontWeight: 'bold'
            }}
          >
            Check Other Options
          </Button>
        </Box>
      </Container>
    </Box>
  )
}

export default HeroSection
