'use client'

import { useEffect } from 'react'

import { useRouter } from 'next/navigation'

import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Grid from '@mui/material/Grid'
import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import { useTheme } from '@mui/material/styles'

import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import StarIcon from '@mui/icons-material/Star'
import PeopleIcon from '@mui/icons-material/People'
import FitnessCenterIcon from '@mui/icons-material/FitnessCenter'
import RestaurantIcon from '@mui/icons-material/Restaurant'
import PsychologyIcon from '@mui/icons-material/Psychology'
import FamilyRestroomIcon from '@mui/icons-material/FamilyRestroom'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import SupportIcon from '@mui/icons-material/Support'

import PricingPage from '@/components/pricing'

export const metadata = {
  title: 'Nutrich.io - What to Eat, Now You Know',
  description:
    'Stop guessing and start glowing. Get unique meal plans generated by artificial intelligence, perfectly tailored to your individual data, goals, and preferences.'
}

const Header = () => {
  const router = useRouter()

  return (
    <header className='bg-white/80 backdrop-blur-md sticky top-0 z-50 shadow-sm'>
      <nav className='container mx-auto px-6 py-4 flex justify-between items-center'>
        <a href='#' className='flex items-center space-x-2'>
          <svg
            width='32'
            height='32'
            viewBox='0 0 24 24'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
            className='text-teal-500'
          >
            <path
              d='M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM16.22 9.39L10.36 15.25C10.16 15.45 9.85 15.45 9.65 15.25L7.78 13.38C7.58 13.18 7.58 12.87 7.78 12.67C7.98 12.47 8.29 12.47 8.49 12.67L10 14.18L15.51 8.67C15.71 8.47 16.02 8.47 16.22 8.67C16.42 8.87 16.42 9.19 16.22 9.39Z'
              fill='url(#logo-gradient)'
            />
            <defs>
              <linearGradient id='logo-gradient' x1='0' y1='0' x2='1' y2='1'>
                <stop offset='0%' stopColor='#007CF0' />
                <stop offset='100%' stopColor='#00DFD8' />
              </linearGradient>
            </defs>
          </svg>
          <span className='text-2xl font-bold gradient-text'>nutrich.io</span>
        </a>
        <div className='hidden md:flex items-center space-x-8'>
          <a href='#landingFeatures' className='text-gray-600 hover:text-blue-600 transition'>
            Features
          </a>
          <a href='#landingServices' className='text-gray-600 hover:text-blue-600 transition'>
            Services
          </a>
          <a href='#landingPricing' className='text-gray-600 hover:text-blue-600 transition'>
            Pricing
          </a>
          <a href='#landingFAQ' className='text-gray-600 hover:text-blue-600 transition'>
            FAQ
          </a>
          <a href='#landingContacts' className='text-gray-600 hover:text-blue-600 transition'>
            Contacts
          </a>
        </div>
        <Button
          variant='contained'
          color='primary'
          className='hidden md:inline-block font-semibold px-5 py-2 shadow-md'
          sx={{ borderRadius: 2 }}
          onClick={() => router.push('/register')}
        >
          Register
        </Button>
      </nav>
    </header>
  )
}

const Footer = () => (
  <footer className='bg-gray-900 text-white'>
    <div className='container mx-auto px-6 py-12'>
      <div className='grid md:grid-cols-4 gap-8'>
        <div className='col-span-2 md:col-span-1'>
          <h3 className='text-lg font-bold'>nutrich.io</h3>
          <p className='mt-2 text-gray-400'>What to eat? Now you know.</p>
        </div>
        <div>
          <h3 className='text-lg font-semibold'>Links</h3>
          <ul className='mt-4 space-y-2'>
            <li>
              <a href='#landingFeatures' className='text-gray-400 hover:text-white'>
                Features
              </a>
            </li>
            <li>
              <a href='#landingServices' className='text-gray-400 hover:text-white'>
                Services
              </a>
            </li>
            <li>
              <a href='#landingPricing' className='text-gray-400 hover:text-white'>
                Pricing
              </a>
            </li>
          </ul>
        </div>
        <div>
          <h3 className='text-lg font-semibold'>Legal</h3>
          <ul className='mt-4 space-y-2'>
            <li>
              <a href='#' className='text-gray-400 hover:text-white'>
                Terms of Service
              </a>
            </li>
            <li>
              <a href='#' className='text-gray-400 hover:text-white'>
                Privacy Policy
              </a>
            </li>
          </ul>
        </div>
        <div>
          <h3 className='text-lg font-semibold'>Social</h3>
          <div className='flex space-x-4 mt-4'>
            <a href='#' className='text-gray-400 hover:text-white'>
              <svg className='w-6 h-6' fill='currentColor' viewBox='0 0 24 24' aria-hidden='true'>
                <path
                  fillRule='evenodd'
                  d='M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z'
                  clipRule='evenodd'
                />
              </svg>
            </a>
            <a href='#' className='text-gray-400 hover:text-white'>
              <svg className='w-6 h-6' fill='currentColor' viewBox='0 0 24 24' aria-hidden='true'>
                <path d='M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.71v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84' />
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div className='mt-12 border-t border-gray-800 pt-8 text-center text-gray-500'>
        <p>&copy; 2025 Nutrich.io. All rights reserved.</p>
      </div>
    </div>
  </footer>
)

const LandingPage = () => {
  const theme = useTheme()

  const gradientTextStyle = {
    background: 'linear-gradient(to right, #007CF0, #00DFD8)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text'
  }

  const sectionSubtitleStyle = {
    fontSize: '0.875rem',
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: '#007CF0'
  }

  const features = [
    {
      icon: <RestaurantIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'Your Flexible Health Wallet',
      description:
        'Purchase tokens with ease and use them for any service you want, whenever you want. Your balance never expires.'
    },
    {
      icon: <SupportIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'Your Personal Result Center',
      description:
        'All purchased meal plans and recipes are automatically saved and always available in your personal account.'
    },
    {
      icon: <PsychologyIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'Intelligent Personalization',
      description:
        'Our AI analyzes your unique data—height, weight, age, and goals—to calculate your optimal daily calorie intake with precision.'
    },
    {
      icon: <FamilyRestroomIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'Family & Couples Plans',
      description:
        'Generate a shared meal plan for two or more people with different goals, with smart portion sizes for each person.'
    },
    {
      icon: <AutoAwesomeIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'Healthy Alternatives',
      description:
        'Craving something unhealthy? Our AI assistant helps you stay on track by offering a healthy and delicious alternative.'
    },
    {
      icon: <FitnessCenterIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'AI Plan Adaptation',
      description:
        'Missing an ingredient? The AI can change a recipe on the fly while maintaining the required nutritional balance.'
    }
  ]

  const targetAudience = [
    {
      icon: <PeopleIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'For Busy Professionals',
      description:
        'Save time and mental energy. Get your weekly meals planned out so you can focus on your work, knowing your nutrition is optimized for performance.'
    },
    {
      icon: <FamilyRestroomIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'For Families & Couples',
      description:
        'Finally solve the &ldquo;what to cook for everyone&rdquo; problem. Our Family Plan service generates shared meals with clever recipe changes for everyone.'
    },
    {
      icon: <FitnessCenterIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'For Fitness Enthusiasts',
      description:
        'Dial in your nutrition with precision. Our system accurately calculates macros to help you reach your specific fitness goals.'
    },
    {
      icon: <StarIcon sx={{ fontSize: 40, color: '#007CF0' }} />,
      title: 'For a Healthier Lifestyle',
      description:
        'Get started easily. Simply provide your data and preferences, and let our AI guide you. All plans are saved in your personal account.'
    }
  ]

  const services = [
    {
      title: '1. Flexible Personal Plans',
      description:
        'Our flagship service, designed for the individual user who seeks a truly tailored nutritional guide. Order a plan for a single day, a full week, or an entire month.',
      features: [
        'Custom Calculation: Analyzes your parameters for optimal calorie intake.',
        'Detailed Nutritional Info: Precise breakdown of calories, proteins, fats, and carbs.',
        'User-Centric: Built on your data and personal food preferences.'
      ]
    },
    {
      title: '2. Family or Couples Plan',
      description:
        'Solves the common problem of what to cook for a household with multiple people who have different tastes and dietary goals.',
      features: [
        'Shared Meals, Custom Portions: AI suggests different serving sizes for each person.',
        'Diverse Goal Management: Accommodates different goals simultaneously.'
      ]
    },
    {
      title: '3. Specialized Programs',
      description:
        'Ready-made, packaged meal plans designed for a specific, focused purpose, like a "7-day Detox" or a "2 Week Marathon Meal Plan".',
      features: [
        'Goal-Oriented: Targeted programs for clear, time-sensitive goals.',
        'Fixed Product: Sold as a complete package for a simple purchase decision.'
      ]
    },
    {
      title: '4. Interactive AI Assistants',
      description:
        'Transforms the platform into a true "daily nutrition assistant" by allowing you to modify your plans on the fly.',
      features: [
        "AI Plan Adaptation: Instantly change a recipe if you're missing ingredients.",
        'Healthy Alternative Creator: Get healthy swaps for unhealthy cravings.'
      ]
    }
  ]

  const testimonials = [
    {
      text: "The Family Plan is a lifesaver. My husband is trying to lose weight, I'm a vegetarian, and our son just wants tasty food. Nutrich.io creates one menu for all of us. It's brilliant!",
      author: 'Anna K.',
      role: 'Mom & Busy Professional'
    },
    {
      text: 'I\'m down 4 kg in my first month, and I never felt like I was on a diet. The "What if..." AI assistant is the best part. This is the first plan I\'ve actually been able to stick to.',
      author: 'Mark T.',
      role: 'User since June 2025'
    },
    {
      text: 'I bought the "2 Week Marathon Meal Plan" and the results were incredible. All my plans are saved in my personal account, so I can go back to my favorite meals anytime. Highly recommended!',
      author: 'Elena P.',
      role: 'Fitness Enthusiast'
    }
  ]

  const faqs = [
    {
      question: 'How It Works?',
      answer:
        "We've made the process as simple as possible: 1) Create Your Account & Profile: Register in seconds and tell our AI your goals. 2) Choose Your Token Package: Top up your balance with tokens that never expire. 3) Get Your AI-Generated Plan: Use tokens to order any service and get your plan instantly."
    },
    {
      question: 'How are the meal plans created?',
      answer:
        'Our plans are generated by artificial intelligence based on the individual data you provide. The system precisely calculates your optimal daily calorie intake for healthy results.'
    },
    {
      question: 'What are tokens and do they expire?',
      answer:
        'Tokens are the internal currency of Nutrich.io. You purchase token packages to top up your balance, and then use those tokens to buy any service you want. Your tokens never expire.'
    },
    {
      question: 'Can I use this service with my family?',
      answer:
        'Yes! Our Family and Couples plan is a flagship service that allows you to generate a shared meal plan for multiple people with different goals, tastes, and even dietary restrictions.'
    },
    {
      question: 'Where can I find my purchased plans?',
      answer:
        'All purchased meal plans, programs, and recipes are automatically saved and always available for you in the "Result Center" of your personal account.'
    }
  ]

  const stats = [
    { value: '1,900', label: 'Kcal calculated for a user wanting to lose 5 kg in a month.' },
    { value: '3', label: 'Unique meal variations for one family dinner.' },
    { value: '<60s', label: 'Time it takes to register and create your personal profile.' },
    { value: '10+', label: 'Specialized programs and AI assistants available.' }
  ]

  return (
    <>
      <Header />
      {/* Hero Section */}
      <Box id='landingHero' sx={{ py: { xs: 10, md: 16 }, textAlign: 'center' }}>
        <Container maxWidth='lg'>
          <Typography
            variant='h2'
            component='h1'
            sx={{
              fontSize: { xs: '2.5rem', md: '4rem' },
              fontWeight: 900,
              mb: 3,
              lineHeight: 1.2
            }}
          >
            <span style={gradientTextStyle}>NUTRICH.IO</span>
            <br />
            What to Eat? Now You Know.
          </Typography>
          <Typography
            variant='h6'
            sx={{
              color: 'text.secondary',
              maxWidth: '800px',
              mx: 'auto',
              mb: 5
            }}
          >
            Stop guessing and start glowing. Get unique meal plans generated by artificial intelligence, perfectly
            tailored to your individual data, goals, and preferences. Transform your health with your own daily
            nutrition assistant.
          </Typography>
          <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Button
              variant='contained'
              size='large'
              sx={{
                background: 'linear-gradient(to right, #007CF0, #00DFD8)',
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                fontWeight: 'bold'
              }}
            >
              Create My Personal Plan
            </Button>
            <Button
              variant='outlined'
              size='large'
              sx={{
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                fontWeight: 'bold'
              }}
            >
              Check Other Options
            </Button>
          </Box>
        </Container>
      </Box>

      {/* Mission Section */}
      <Box sx={{ py: 10, bgcolor: 'white' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center' }}>
            <Typography sx={sectionSubtitleStyle}>OUR MISSION</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 3 }}>
              Beyond the Plan: Your Daily Partner in Health
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '800px', mx: 'auto' }}>
              Our key strategic objective is to be more than just a website you visit once. We aim to transform our
              service from a &ldquo;one-time plan generator&rdquo; into your &ldquo;daily nutrition assistant&rdquo;. We
              believe that true health is an ongoing journey, which is why our AI provides interactive tools that adapt
              to your life, empowering you to build lasting, healthy habits on your own terms.
            </Typography>
          </Box>
        </Container>
      </Box>

      {/* Who Is This For Section */}
      <Box sx={{ py: 10, bgcolor: 'grey.50' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mb: 2 }}>
              Designed For Your Unique Life
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto' }}>
              Whether you&apos;re a busy professional, a family manager, or a fitness enthusiast, nutrich.io is built to
              adapt to your specific needs.
            </Typography>
          </Box>
          <Grid container spacing={4}>
            {targetAudience.map((item, index) => (
              <Grid item xs={12} md={6} lg={3} key={index}>
                <Card sx={{ height: '100%', textAlign: 'center', p: 4, bgcolor: 'white' }}>
                  <Box sx={{ mb: 2 }}>{item.icon}</Box>
                  <Typography variant='h6' sx={{ fontWeight: 'bold', mb: 2 }}>
                    {item.title}
                  </Typography>
                  <Typography variant='body2' sx={{ color: 'text.secondary' }}>
                    {item.description}
                  </Typography>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* Features Section */}
      <Box id='landingFeatures' sx={{ py: 10, bgcolor: 'white' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography sx={sectionSubtitleStyle}>YOUR PERSONAL NUTRITION OS</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 3 }}>
              A Smarter Way to Plan Your Day
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '800px', mx: 'auto' }}>
              Go beyond static &ldquo;one-time&rdquo; plans. Our service is designed to be your daily partner in health,
              providing dynamic and intelligent solutions for every nutritional challenge.
            </Typography>
          </Box>
          <Grid container spacing={4}>
            {features.map((feature, index) => (
              <Grid item xs={12} md={6} lg={4} key={index}>
                <Card sx={{ height: '100%', p: 4, bgcolor: 'grey.50' }}>
                  <Box sx={{ mb: 3 }}>{feature.icon}</Box>
                  <Typography variant='h6' sx={{ fontWeight: 'bold', mb: 2 }}>
                    {feature.title}
                  </Typography>
                  <Typography variant='body2' sx={{ color: 'text.secondary' }}>
                    {feature.description}
                  </Typography>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* Services Section */}
      <Box id='landingServices' sx={{ py: 10 }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography sx={sectionSubtitleStyle}>OUR SERVICES</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 3 }}>
              One Platform, Every Nutritional Need
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto' }}>
              From solo plans to family solutions and specialized programs, we have a service for every goal and
              lifestyle.
            </Typography>
          </Box>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {services.map((service, index) => (
              <Grid container spacing={6} key={index} alignItems='center'>
                <Grid item xs={12} md={6} order={{ xs: 1, md: index % 2 === 0 ? 1 : 2 }}>
                  <Typography variant='h5' sx={{ fontWeight: 'bold', mb: 2 }} style={gradientTextStyle}>
                    {service.title}
                  </Typography>
                  <Typography variant='body1' sx={{ color: 'text.secondary', mb: 3 }}>
                    {service.description}
                  </Typography>
                </Grid>
                <Grid item xs={12} md={6} order={{ xs: 2, md: index % 2 === 0 ? 2 : 1 }}>
                  <Card sx={{ p: 3 }}>
                    <Box component='ul' sx={{ listStyle: 'none', p: 0, m: 0 }}>
                      {service.features.map((feature, featureIndex) => (
                        <Box
                          component='li'
                          key={featureIndex}
                          sx={{ display: 'flex', alignItems: 'flex-start', mb: 2 }}
                        >
                          <CheckCircleIcon sx={{ color: '#00DFD8', mr: 2, mt: 0.5, flexShrink: 0 }} />
                          <Typography variant='body2' sx={{ color: 'text.secondary' }}>
                            {feature}
                          </Typography>
                        </Box>
                      ))}
                    </Box>
                  </Card>
                </Grid>
              </Grid>
            ))}
          </Box>
        </Container>
      </Box>

      {/* Statistics Section */}
      <Box sx={{ py: 10, bgcolor: 'white' }}>
        <Container maxWidth='lg'>
          <Grid container spacing={4}>
            {stats.map((stat, index) => (
              <Grid item xs={12} md={3} key={index}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant='h3' sx={{ fontWeight: 900, mb: 2 }} style={gradientTextStyle}>
                    {stat.value}
                  </Typography>
                  <Typography variant='body2' sx={{ color: 'text.secondary' }}>
                    {stat.label}
                  </Typography>
                </Box>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* Pricing Section */}
      <Box id='landingPricing' sx={{ py: 10, bgcolor: 'grey.50' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography sx={sectionSubtitleStyle}>PRICING PLANS</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 2 }}>
              Choose Your Fuel. Simple, Flexible & Forever.
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto', mb: 0 }}>
              Tokens are your internal currency for any service on Nutrich.io. Top up your balance, use them whenever
              you want, and remember—<b>your tokens never expire</b>.
            </Typography>
          </Box>
          <PricingPage title={false} />
        </Container>
      </Box>

      {/* Testimonials Section */}
      <Box sx={{ py: 10, bgcolor: 'white' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography sx={sectionSubtitleStyle}>TESTIMONIALS</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 3 }}>
              What People Say
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto' }}>
              See what our customers have to say about their experience.
            </Typography>
          </Box>
          <Grid container spacing={4}>
            {testimonials.map((testimonial, index) => (
              <Grid item xs={12} md={4} key={index}>
                <Card sx={{ p: 4, bgcolor: 'grey.50', height: '100%' }}>
                  <Typography variant='body2' sx={{ color: 'text.secondary', mb: 3 }}>
                    &ldquo;{testimonial.text}&rdquo;
                  </Typography>
                  <Box>
                    <Typography variant='subtitle1' sx={{ fontWeight: 'bold' }}>
                      {testimonial.author}
                    </Typography>
                    <Typography variant='caption' sx={{ color: 'text.secondary' }}>
                      {testimonial.role}
                    </Typography>
                  </Box>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* FAQ Section */}
      <Box id='landingFAQ' sx={{ py: 10 }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center', mb: 8 }}>
            <Typography sx={sectionSubtitleStyle}>FAQ</Typography>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mt: 1, mb: 3 }}>
              Frequently Asked Questions
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto' }}>
              Have questions? We&apos;ve got answers. If you can&apos;t find what you&apos;re looking for, feel free to
              contact us.
            </Typography>
          </Box>
          <Box sx={{ maxWidth: '800px', mx: 'auto' }}>
            {faqs.map((faq, index) => (
              <Card key={index} sx={{ mb: 3, p: 3 }}>
                <Typography variant='h6' sx={{ fontWeight: 600, mb: 2 }}>
                  {faq.question}
                </Typography>
                <Typography variant='body2' sx={{ color: 'text.secondary' }}>
                  {faq.answer}
                </Typography>
              </Card>
            ))}
          </Box>
        </Container>
      </Box>

      {/* CTA Section */}
      <Box id='landingContacts' sx={{ py: 10, bgcolor: 'white' }}>
        <Container maxWidth='lg'>
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant='h3' sx={{ fontWeight: 'bold', mb: 3 }}>
              Ready to Transform Your Nutrition?
            </Typography>
            <Typography variant='body1' sx={{ color: 'text.secondary', maxWidth: '600px', mx: 'auto', mb: 4 }}>
              Stop wondering, start knowing. Your personal AI nutrition assistant is waiting. Create your free account
              today and discover how easy healthy eating can be.
            </Typography>
            <Button
              variant='contained'
              size='large'
              sx={{
                background: 'linear-gradient(to right, #007CF0, #00DFD8)',
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                fontWeight: 'bold'
              }}
            >
              Register for Free with Google
            </Button>
          </Box>
        </Container>
      </Box>
      <Footer />
      <style>{`
  .gradient-text {
    background: linear-gradient(to right, #007CF0, #00DFD8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }
  html {
    scroll-behavior: smooth;
  }
`}</style>
    </>
  )
}

export default LandingPage
