'use client'

import { useState, useEffect } from 'react'

import {
  Header,
  Footer,
  HeroSection,
  MissionSection,
  TargetAudienceSection,
  FeaturesSection,
  ServicesSection,
  StatisticsSection,
  PricingSection,
  TestimonialsSection,
  FAQSection,
  CTASection
} from './components'

export const metadata = {
  title: 'Nutrich.io - What to Eat, Now You Know',
  description:
    'Stop guessing and start glowing. Get unique meal plans generated by artificial intelligence, perfectly tailored to your individual data, goals, and preferences.'
}

const LandingPage = () => {
  // States
  const [mode, setMode] = useState('light')

  // Mode o'zgarishini qabul qilish
  const handleModeChange = newMode => {
    setMode(newMode)
  }

  return (
    <div id='landingHero'>
      <Header onModeChange={handleModeChange} />
      <HeroSection mode={mode} />
      <MissionSection mode={mode} />
      <TargetAudienceSection mode={mode} />
      <FeaturesSection mode={mode} />
      <ServicesSection mode={mode} />
      <StatisticsSection mode={mode} />
      <PricingSection mode={mode} />
      <TestimonialsSection mode={mode} />
      <FAQSection mode={mode} />
      <CTASection mode={mode} />
      <Footer mode={mode} />
      <style>{`
  .gradient-text {
    background: linear-gradient(to right, #007CF0, #00DFD8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }
  html {
    scroll-behavior: smooth;
  }
`}</style>
    </div>
  )
}

export default LandingPage
